Noted/Noted/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('main/', include('notes.urls')),
    path('', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Noted/notes/urls.py
from django.urls import path, register_converter
from .views import main_page, main_page_date, all_notes, note_details, note_edit, all_tasks, \
    task_done, trash, task_delete, note_delete, user_settings, change_password, search, note_perm_delete, \
    task_perm_delete, task_undone, tasks, note_pin, note_unpin, send_note, task_restore, note_restore, user_delete, date_picker
from .path_converters import DateConverter


register_converter(DateConverter, 'date')


urlpatterns = [
    path('', main_page, name='main'),
    path('<date:date>/', main_page_date, name='date_notes'),
    path('notes', all_notes, name='notes'),
    path('notes/<int:pk>', note_details, name='note_details'),
    path('notes/edit/<int:pk>', note_edit, name='note_edit'),
    path('<date:date>/pin/<int:pk>', note_pin, name='note_pin'),
    path('<date:date>/unpin/<int:pk>', note_unpin, name='note_unpin'),
    path('tasks/', tasks, name='tasks'),
    path('tasks/<date:date>/', all_tasks, name='tasks_date'),
    path('tasks/<date:date>/edit/<int:pk>', all_tasks, name='task_edit'),
    path('done/<int:pk>', task_done, name='task_done'),
    path('undone/<int:pk>', task_undone, name='task_undone'),
    path('task_delete/<int:pk>', task_delete, name='task_delete'),
    path('note_delete/<int:pk>', note_delete, name='note_delete'),
    path('note_perm_delete/<int:pk>', note_perm_delete, name='note_perm_delete'),
    path('task_perm_delete/<int:pk>', task_perm_delete, name='task_perm_delete'),
    path('trash', trash, name='trash'),
    path('settings', user_settings, name='user_settings'),
    path('settings/change_password', change_password, name='change_password'),
    path('search', search, name='search'),
    path('send/<int:pk>', send_note, name='send_note'),
    path('task_restore/<date:date>/<int:pk>', task_restore, name='task_restore'),
    path('note_restore/<int:pk>', note_restore, name='note_restore'),
    path('user_delete', user_delete, name='user_delete'),
    path('date_picker', date_picker, name='date_picker'),
    ]

Noted/notes/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    task_title = models.CharField(max_length=1000)
    task_author = models.ForeignKey(User, on_delete=models.CASCADE)
    task_date = models.DateField()
    add_at = models.DateTimeField(blank=True)
    task_time = models.TimeField(blank=True, null=True)
    #task_timestamp = models.DateTimeField(blank=True, null=True)
    task_priority = models.BooleanField(default=False)
    task_deleted = models.BooleanField(default=False)
    task_trash = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.task_title}'

    def get_absolute_url(self):
        return f'/main/{self.id}'


# class TaskNotification(models.Model):
#     task = models.OneToOneField(Task, on_delete=models.CASCADE)
#     task_timestamp = models.DateTimeField(blank=True, null=True)


class Note(models.Model):
    note_title = models.CharField(max_length=250)
    note_text = models.TextField()
    note_date = models.DateField(blank=True, null=True)
    add_at = models.DateTimeField(blank=True)
    note_author = models.ForeignKey(User, on_delete=models.CASCADE)
    note_trash = models.BooleanField(default=False)
    note_file = models.FileField(null=True, blank=True, upload_to='documents')
    note_pin = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.note_title}'

    def get_absolute_url(self):
        return f'/main/{self.id}'


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='/avatars/Noted_avatar.png', upload_to='avatars')
    name = models.CharField(max_length=20, default='Username')

    def __str__(self):
        return self.user.username

Noted/notes/forms.py
from django.forms import ModelForm
from .models import Task, UserProfile
from django import forms
from django.contrib.auth.models import User
from .validators import EmailValidator
from django.utils.translation import gettext_lazy as _


# форма для добавления задачи
class TaskForm(ModelForm):
    task_title = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Добавьте название...')}))
    task_date = forms.DateField(label='', widget=forms.widgets.DateInput(attrs={'type': 'date', 'class': 'date-widget',
                                                'style': 'border-radius: 0.375rem; padding: 4px 13px; font-size: 15px; background: rgba(255, 255, 255, 0.8);'}))
    task_time = forms.TimeField(label='', required=False, widget=forms.widgets.TimeInput(attrs={'type': 'time', 'class': 'time-widget',
                                                                                'style': 'border-radius: 0.375rem; border: none; padding: 3px 12px; background: rgba(255, 255, 255, 0.8);'}))
    # task_timestamp = forms.CharField(widget=forms.HiddenInput(attrs={}))

    class Meta:
        model = Task
        fields = ['task_title', 'task_date', 'task_time', 'task_priority']


# форма для редактирования данных пользователя
class UpdateUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super(UpdateUserForm, self).__init__(*args, **kwargs)
        user = kwargs.pop('instance')
        self.fields['email'].validators.append(EmailValidator(user))

    class Meta:
        model = User
        fields = ['email', ]


# форма для редактирования аватара
class UpdateProfileForm(forms.ModelForm):
    name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control',  'onchange': 'fileinputChange()', 'style': 'opacity: 0; height: 0;', 'id': 'note-file'}))

    class Meta:
        model = UserProfile
        fields = ['avatar', 'name']

Noted/notes/views.py
from django.shortcuts import render, redirect
from .models import Note, Task
from .forms import TaskForm, UpdateUserForm, UpdateProfileForm
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import login
from django.utils import timezone
from django.core.mail import EmailMessage
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from .validators import validate_password


# страница с яваскриптом, который определяет дату пользователя и делает редирект на главную страницу со всеми заметками и задачами на эту дату
@login_required
def main_page(request):
    return render(request, 'main.html', context={})


# выводит главную страницу со всеми заметками и задачами на конкретную дату
@login_required
def main_page_date(request, date):
    user = request.user
    lang = request.LANGUAGE_CODE
    next_date = date + datetime.timedelta(days=1)
    prev_date = date - datetime.timedelta(days=1)
    tasks_active = Task.objects.filter(task_date=date, task_author=user, task_deleted=False, task_priority=False,
                                       task_trash=False).order_by('task_time')
    tasks_deleted = Task.objects.filter(task_date=date, task_author=user, task_deleted=True, task_trash=False).order_by('add_at')
    tasks_important = Task.objects.filter(task_date=date, task_author=user, task_deleted=False, task_priority=True,
                                          task_trash=False).order_by('task_time')
    notes_pin = Note.objects.filter(note_author=user, note_trash=False, note_pin=True).order_by('-add_at')
    notes = Note.objects.filter(note_author=user, note_trash=False, note_pin=False).order_by('-add_at')
    month_list = [_('января'), _('февраля'), _('марта'), _('апреля'), _('мая'), _('июня'),
                  _('июля'), _('августа'), _('сентября'), _('октября'), _('ноября'), _('декабря')]
    if lang == 'ru':
        date = f'{date.day} {month_list[int(date.month) - 1]}'
    else:
        if date.day in (1, 21, 31):
            date = f'{month_list[int(date.month) - 1]}, {date.day}st'
        elif date.day in (2, 22):
            date = f'{month_list[int(date.month) - 1]}, {date.day}nd'
        elif date.day in (3, 23):
            date = f'{month_list[int(date.month) - 1]}, {date.day}rd'
        else:
            date = f'{month_list[int(date.month) - 1]}, {date.day}th'
    return render(request, 'main2.html', context={'today_tasks': tasks_active, 'tasks_deleted': tasks_deleted,
                                                  'tasks_important': tasks_important, 'notes': notes, 'date': date,
                                                  'next_date': next_date, 'prev_date': prev_date, 'notes_pin': notes_pin})


# выводит страницу со всеми существующими заметками и формой добавления новой
@login_required
def all_notes(request):
    user = request.user
    if request.method == "POST":
        note_title = request.POST['note_title']
        note_text = request.POST['note_text']
        note_date = request.POST['note_date']
        add_at = datetime.datetime.now()
        try:
            note_file = request.FILES['note_file']
            Note.objects.create(note_title=note_title, note_text=note_text, note_author=user,
                                note_file=note_file, add_at=add_at, note_date=note_date)
        except:
            Note.objects.create(note_title=note_title, note_text=note_text, note_author=user,
                                add_at=add_at, note_date=note_date)
        return redirect('notes')
    else:
        notes = Note.objects.filter(note_author=user, note_trash=False, note_pin=False).order_by('-add_at')
        notes_pin = Note.objects.filter(note_author=user, note_trash=False, note_pin=True).order_by('-add_at')
        return render(request, 'notes.html', context={'notes': notes, 'notes_pin': notes_pin})


# выводит страницу со всеми существующими заметками и одной конкретной заметкой в полноэкранном режиме
@login_required
def note_details(request, pk):
    user = request.user
    notes = Note.objects.filter(note_author=user, note_trash=False, note_pin=False).order_by('-add_at')
    notes_pin = Note.objects.filter(note_author=user, note_trash=False, note_pin=True).order_by('-add_at')
    note = Note.objects.get(id=pk)
    return render(request, 'note_details.html', context={'notes': notes, 'note': note, 'notes_pin': notes_pin})


# выводит страницу со всеми существующими заметками и формой редактирования одной конкретной заметки
@login_required
def note_edit(request, pk):
    user = request.user
    if request.method == "POST":
        note_title = request.POST['note_title']
        note_text = request.POST['note_text']
        note_date = request.POST['note_date']
        file_delete = request.POST.get('file_delete', False)
        add_at = datetime.datetime.now()
        if file_delete == 'on':
            Note.objects.filter(id=pk).update(note_file=None, note_trash=False)
        try:
            note_file = request.FILES['note_file']
            note = Note.objects.get(id=pk)
            note.note_file = note_file
            note.note_title = note_title
            note.note_text = note_text
            note.note_date = note_date
            note.add_at = add_at
            note.save()
        except:
            Note.objects.filter(id=pk).update(note_title=note_title, note_text=note_text, add_at=add_at, note_date=note_date, note_trash=False)
        return redirect('notes')
    else:
        note = Note.objects.get(id=pk)
        notes = Note.objects.filter(note_author=user, note_trash=False, note_pin=False).order_by('-add_at')
        notes_pin = Note.objects.filter(note_author=user, note_trash=False, note_pin=True).order_by('-add_at')
        return render(request, 'note_edit.html', context={'notes': notes, 'note': note, 'notes_pin': notes_pin})


# страница, где определяется текущая дата и происходит редирект на страницу задач на эту дату
@login_required
def tasks(request):
    return render(request, 'tasks_base.html', context={})


# выводит страницу с задачами на текущую дату и формой добавления новой либо формой редактирования старой
@login_required
def all_tasks(request, date, pk=None):
    user = request.user
    tasks_active = Task.objects.filter(task_date=date, task_author=user, task_deleted=False, task_priority=False,
                                       task_trash=False).order_by('task_time')
    tasks_deleted = Task.objects.filter(task_date=date, task_author=user, task_deleted=True, task_trash=False).order_by('add_at')
    tasks_important = Task.objects.filter(task_date=date, task_author=user, task_deleted=False, task_priority=True,
                                          task_trash=False).order_by('task_time')
    task2 = None
    try:
        task2 = Task.objects.get(id=pk)
        form = TaskForm(instance=task2)
    except:
        form = TaskForm()

    if request.method == "POST":
        task_title = request.POST['task_title']
        task_date = request.POST['task_date']
        task_time = request.POST['task_time']
        task_priority = request.POST.get('priority', False)
        add_at = timezone.now()
        if task_priority:
            task_priority = True
        try:
            task = Task.objects.get(id=pk)
            if task_time == '':
                Task.objects.filter(id=pk).update(task_title=task_title, task_priority=task_priority, task_date=task_date,
                                              add_at=add_at)
            else:
                Task.objects.filter(id=pk).update(task_title=task_title, task_priority=task_priority,
                                                  task_date=task_date, add_at=add_at, task_time=task_time)
        except:
            if task_time == '':
                Task.objects.create(task_title=task_title, task_priority=task_priority, task_author=user,
                                task_date=task_date, add_at=add_at)
            else:
                Task.objects.create(task_title=task_title, task_priority=task_priority, task_author=user,
                                    task_date=task_date, add_at=add_at, task_time=task_time)
        return redirect('tasks')

    return render(request, 'tasks.html', context={'today_tasks': tasks_active, 'tasks_deleted': tasks_deleted,
                                                      'tasks_important': tasks_important, 'form': form, 'task': pk,  'task2': task2})


# функция для зачеркивания задачи при нажатии на кружок
@login_required
def task_done(request, pk):
    Task.objects.filter(id=pk).update(task_deleted=True)
    next = request.GET.get('next', reverse('main'))
    return HttpResponseRedirect(next)


# функция для восстановления задачи при нажатии на отмеченный кружок
@login_required
def task_undone(request, pk):
    Task.objects.filter(id=pk).update(task_deleted=False)
    next = request.GET.get('next', reverse('main'))
    return HttpResponseRedirect(next)


# выводит корзину с удаленными задачами и заметками
@login_required
def trash(request):
    user = request.user
    task_trash = Task.objects.filter(task_author=user, task_trash=True)
    note_trash = Note.objects.filter(note_author=user, note_trash=True)
    return render(request, 'trash.html', context={'task_trash': task_trash, 'note_trash': note_trash})


# функция для удаления задачи в корзину при нажатии на иконку мусорной корзины
@login_required
def task_delete(request, pk):
    Task.objects.filter(id=pk).update(task_trash=True)
    next = request.GET.get('next', reverse('main'))
    return HttpResponseRedirect(next)


# функция для удаления заметки в корзину при нажатии на иконку мусорной корзины
@login_required
def note_delete(request, pk):
    Note.objects.filter(id=pk).update(note_trash=True)
    next = request.GET.get('next', reverse('notes'))
    return HttpResponseRedirect(next)

Noted/templates/date_picker.html
{% extends "default.html" %}
{% load i18n %}
{% block title %}
DatePicker Widget
{% endblock title %}

{% block content %}
    <div class="datepicker-wrapper">
        <div class="select-date" onclick="datepickerToggler()">
            <input type="text" placeholder="Выберите дату" name="task_date" class="form-control" id="id_task_date" style="cursor: pointer;">
            <span class="eye"><a><img width="25px" height="25px" id="togglePicker" src="/static/images/icons/calendar_icon.svg"/></a></span>
        </div>
        <div class="calendar-wrapper2" style="margin: 0;">
            <button id="btnPrev" type="button" style="margin-top: 15px;"></button>
            <h6 id="headCal"></h6>
            <button id="btnNext" type="button"></button>
            <div id="divCal"></div>
        </div>
    </div>
    <div>The cap-independent translation of plus-strand RNA plant viruses frequently depends on 3′ structures to attract translation initiation factors that bind ribosomal subunits or bind directly to ribosomes. Umbraviruses are excellent models for studying 3′ cap-independent translation enhancers (3′CITEs), as umbraviruses can have different 3′CITEs in the central region of their lengthy 3′UTRs, and most also have a particular 3′CITE (the T-shaped structure or 3′TSS) near their 3′ ends. We discovered a novel hairpin just upstream of the centrally located (known or putative) 3′CITEs in all 14 umbraviruses. These CITE-associated structures (CASs) have conserved sequences in their apical loops and at the stem base and adjacent positions. In 11 umbraviruses, CASs are preceded by two small hairpins joined by a putative kissing loop interaction (KL). Converting the conserved 6-nt apical loop to a GNRA tetraloop in opium poppy mosaic virus (OPMV) and pea enation mosaic virus 2 (PEMV2) enhanced translation of genomic (g)RNA, but not subgenomic (sg)RNA reporter constructs, and significantly repressed virus accumulation in Nicotiana benthamiana. Other alterations throughout OPMV CAS also repressed virus accumulation and only enhanced sgRNA reporter translation, while mutations in the lower stem repressed gRNA reporter translation. Similar mutations in the PEMV2 CAS also repressed accumulation but did not significantly affect gRNA or sgRNA reporter translation, with the exception of deletion of the entire hairpin, which only reduced translation of the gRNA reporter. </div>

<script src="/static/js/datePicker.js"></script>

{% endblock content %}

Noted/templates/default.html
<!--шаблон для head, header и footer для страниц пользователя с формой поиска в header-->
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    {% load static %}
    {% load i18n %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/myscripts.js' %}"></script>
    <link rel="icon" href="{% static 'images/Noted_favicon.png' %}" type="image/pgn">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Didact+Gothic&family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a5853bef6b.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <title>
        {% block title %}
        {% endblock title %}
    </title>

</head>
<body>
    <header>
        <div class="container-xxl header-area" >
            <div class="row align-items-center" style="height: 70px;">
                <div class="col-2 col-lg-6 logo-div">
                    <a href="{% url 'main' %}"><img src="/static/images/Noted_colour_full_RGB.png" alt="Logo" width="140" height="60"></a>
                </div>
                <div class="col-8 col-lg-5 search-wrapper">
                    <form action="{% url 'search' %}" method="get">
                        <div class="input-search">
                            <input type="search" name="q" class="header-search form-control" placeholder="{% trans 'Поиск' %}" />
                            <span class="icon"><img width="20" height="20" src="/static/images/icons/search_icon.svg" /></i></span>
                        </div>
                    </form>
                </div>
                <div class="col-2 col-lg-1 lang-mob" style="padding: 0 25px;">
                    <form action="{% url 'set_language' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ redirect_to }}">
                        <div>
                        <select name="language" id="lang_select" class="form-control lang-select" onchange="this.form.submit()">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected="selected" {% endif %}>
                                    {{ language.code }}
                                </option>
                            {% endfor %}
                        </select>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>
    {% block content %}
    {% endblock content %}
    <footer>
        <div class="container-xxl" style="background: rgba(255, 255, 255, 0.8);
                box-shadow: inset 0px 2px 4px rgba(0, 0, 0, 0.25); font-size: 15px; color: #282a25;">
            <div style=" display: flex; flex-direction: column; align-items: center;">
                <p class="text-center mb-0" style="line-height:32px;">{% trans "Данное приложение разработано в рамках проекта" %} <a href="#" style="color: #282a25;">Pineapple Practice</a></p>
            </div>
        </div>
    </footer>

<script type="text/javascript">
window.onload = function() {
    if (window.innerWidth < 992) {
        document.getElementById("offcanvasResponsive").classList.add('offcanvas-end');
    }
}
</script>

<script type="text/javascript">
    window.addEventListener('resize', function(event) {
        if (window.innerWidth < 992) {
            document.getElementById("offcanvasResponsive").classList.add('offcanvas-end');
            }
        else {
            document.getElementById("offcanvasResponsive").classList.remove('offcanvas-end');
            document.getElementById("offcanvasResponsive").style.visibility= "visible";
            }
}, true);
</script>

<script src="/static/js/calendarWidget.js"></script>

<script>
    var calendar = document.getElementsByClassName('calendar-wrapper')[0];
    var drop_but = document.getElementById('drop_but');
    const dropdownPr = document.getElementsByClassName('dropdown')[0];
    dropdownPr.addEventListener('shown.bs.dropdown', () => {
        drop_but.style.display = "none";
        calendar.style.margin = "130px 25px 0px 25px";
    })
    dropdownPr.addEventListener('hidden.bs.dropdown', () => {
        drop_but.style.display = "flex";
        calendar.style.margin = "70px 25px 0px 25px";
    })
</script>

</body>
</html>

Noted/templates/default2.html
<!--шаблон для head, header и footer для страниц авторизации без формы поиска в header-->
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    {% load static %}
    {% load i18n %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/myscripts.js' %}"></script>
    <link rel="icon" href="{% static 'images/Noted_favicon.png' %}" type="image/pgn">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Didact+Gothic&family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a5853bef6b.js" crossorigin="anonymous"></script>

    <title>
        {% block title %}
        {% endblock title %}
    </title>

</head>
<body>
    <header>
        <div class="container-xxl text-center header-area" >
            <div class="row align-items-center justify-content-between" style="height: 70px;">
                <div class="col-auto me-auto">
                    <a href="{% url 'login' %}"><img src="/static/images/Noted_colour_full_RGB.png" alt="Logo" width="140" height="60"></a>
                </div>
                <div class="col-3 col-lg-1" style="padding: 0 25px;">
                    <form action="{% url 'set_language' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ redirect_to }}">
                        <div>
                        <select name="language" id="lang_select" class="form-control lang-select" onchange="this.form.submit()">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected="selected" {% endif %}>
                                    {{ language.code }}
                                </option>
                            {% endfor %}
                        </select>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>
    {% block content %}
    {% endblock content %}
    <footer>
        <div class="container-xxl" style="background: rgba(255, 255, 255, 0.8);
                box-shadow: inset 0px 2px 4px rgba(0, 0, 0, 0.25); font-size: 15px; color: #282a25;">
            <div style=" display: flex; flex-direction: column; align-items: center;">
                <p class="text-center mb-0" style="line-height:32px;">{% trans "Данное приложение разработано в рамках проекта" %} <a href="#" style="color: #282a25;">Pineapple Practice</a></p>
            </div>
        </div>
    </footer>
</body>
</html>

Noted/templates/login.html
{% extends "default2.html" %}
{% load i18n %}
{% block title %}
Войти
{% endblock title %}

{% block content %}

<main>
    <div class="container-xxl main-area">
        <div class="col-10 offset-1 col-lg-4 offset-lg-4 form-block">
            <p class="auth-header">{% trans "Авторизация" %}</p>
            <form method="post" action="{% url 'login' %}" class="form-area">
            {% csrf_token %}
                <div class="mb-3">
                    <input required type="email" class="form-control my-inp" name="email" placeholder="E-mail">
                </div>
                <div id="pass-inp">
                    <input type="password" class="form-control my-inp" id="id_password1" name="password" placeholder="{% trans 'Пароль' %}">
                    <span class="eye"><a onclick="togglePassword()"><img width="25px" height="25px" id="togglePassword" src="/static/images/icons/eye_closed.svg"/></a></span>
                </div>
                <div class="row gx-0 rem-but">
                    <div class="col-auto me-auto mb-3 form-check" style="margin-top: 16px;">
                        <input type="checkbox" name="remember_me" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">{% trans "Запомнить" %}</label>
                    </div>
                    <div class="col-auto button-wrapper" style="margin: 10px 0px 10px; ">
                    <button type="submit" class="btn sm-but">{% trans "Войти" %}</button>
                    </div>
                </div>
            </form>
            <div class="row" id="reg-res">
                <div class="col-auto me-auto">
                    <a href="{% url 'signup' %}">{% trans "Регистрация" %}</a>
                </div>
                <div class="col-auto">
                    <a href="{% url 'reset_password' %}">{% trans "Забыли пароль" %}?</a>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

Noted/templates/registration.html
{% extends "default2.html" %}
{% load i18n %}
{% block title %}
Регистрация
{% endblock title %}

{% block content %}

<main>
    <div class="container-xxl main-area">
        <div class="col-10 offset-1 col-lg-4 offset-lg-4 form-block">
            <p class="auth-header">{% trans "Регистрация" %}</p>
            {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible" role="alert" style="margin-bottom: 20px !important;">
                        <div id="form_errors">
                            {% for key, value in form.errors.items %}
                                <strong>{{ value }}</strong>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            <form method="post" class="form-area">
                {% csrf_token %}
                {{ form.username }}
               <div style="margin-bottom: 20px;">
                    {{ form.email }}
                </div>
                <div style="margin-bottom: 20px; position: relative;">
                    {{ form.password1 }}
                    <span class="eye"><a onclick="togglePassword()"><img width="25px" height="25px" id="togglePassword" src="/static/images/icons/eye_closed.svg"/></a></span>
                </div>
                <div style="margin-bottom: 20px; position: relative;">
                    {{ form.password2 }}
                    <span class="eye"><a onclick="togglePassword2()"><img width="25px" height="25px" id="togglePassword2" src="/static/images/icons/eye_closed.svg"/></a></span>
                </div>
                <div class="row">
                    <div class="col button-wrapper" style="margin: 10px 0px 10px; ">
                        <button type="submit" class="btn lg-but" style="margin-right: auto; margin-left: auto;" id="form_submit" onclick="subformbtn()">{% trans "Зарегистрироваться" %}</button>
                    </div>
                </div>
             </form>
            <div class="row" id="reg">
                <div style="display: flex; flex-direction: column; align-items: center;">
                    <p>{% trans "Уже есть аккаунт" %}? <a href="{% url 'login' %}">{% trans "Войдите" %}</a></p>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}